# Site Info
title:              "Alireza Fathian"
description:        "My Personal Website"
author_name:        "Alireza Fathian" # change this to your name
logo_url:           https://avatars0.githubusercontent.com/u/49844776?s=400&u=3d9f7512e7989e9bffa26bb0b31cbe616d3cf2d0&v=4 # Get it from GitHub API: https://api.github.com/users/alirezafathian

# Site Settings
url:                https://alirezafathian.github.io  # main url
baseurl:             #/the-plain-academic
permalink:          /:title # Post permalink
timezone:           America/Recife
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed
#new
# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true
resume_theme:                   default
#new

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
collections:
  publications:
    output: true
    permalink: /publications/:name
  projects:
    output: true
    permalink: /projects/:name
  talks:
    output: true
    permalink: /talks/:name
  blog:
    output: true
    permalink: /blog/:name

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      type:         "publications"
    values:
      layout:       "research-post"
  -
    scope:
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      type:         "talks"
    values:
      layout:       "post"
  -
    scope:
      type:         "blog"
    values:
      layout:       "post"
